### ISSUE TITLE
1.18.2 using Fabric/Iris 1.2.6 and Lux-EA-B2-P1.zip - Enderman overlaid with black rectangle

### ISSUE THREAD

**Issue by Geethebluesky** [TechDevOnGitHub/Lux-Shader#4] opened 2022-08-03 19:24 UTC
Hi! I'm not sure what kind of info you need for shader bug reports or if this is related to the other issue I see on this github.

I tried your shaders since Iris has it on their list of fully-compatible ones. Except whenever I see an enderman, it's overlaid with a giant black rectangle (probably because the mob was a few blocks away from me while attacking).

What do you need: hardware report? screenshot? logs (which)? Resource packs? Mod list/versions? Reproducing with a barebones set of mods (which--Fabric, Sodium/Iris and your shaders alone, or...?)

Thanks for your patience with me not knowing this in advance.

**Comment by TechDevOnGitHub** [comment] 2022-08-03 20:09
Hey, thank you for reaching out!

> it's overlaid with a giant black rectangle

What you are describing seems to be an issue with NaNs.
I will be adding this issue to my personal list of current bugs and hopefully fix it until the next release.
In the meantime, you should be able to *reduce* the issue by turning off Bloom in "Post Effects > Bloom: OFF"

> What do you need: hardware report? screenshot? logs (which)? Reso...

For this specific issue all I'd need is a screenshot (which is now not necessary anymore due to your description of the issue) and what hardware, specifically **what GPU driver** you have installed. Mods can also impact the shader and introduce potential bugs, but it's not needed for this specific issue.

I will be creating an issue template for this repository now that the shader is getting more attention on GitHub.

**Comment by Geethebluesky** [comment] 2022-08-06 20:20
I'm on Nvidia Game-ready drivers 511.65 on a GeForce 1070 (not Ti).

I can try updating the drivers if you think that might make a difference. Thanks!

**Comment by TechDevOnGitHub** [comment] 2022-08-07 00:22
Making sure you're up-to-date is generally a good idea before reporting a bug but it's not necessary.

If you do end up fixing it by updating your drivers, please let me know so I can put this bug on a lower priority, otherwise I'll get it fixed as soon as possible.

**Comment by TechDevOnGitHub** [comment] 2022-08-16 13:34
Hey, so thanks to @Lolothepro I have come across [this issue](https://github.com/IrisShaders/Iris/issues/1517).

If this really only happens in Iris and not OptiFine, the fix described there might resolve the issue, which would mean it's not an issue with the shader, but with Iris instead.

**Comment by Geethebluesky** [comment] 2022-08-19 16:11
I finally have more than one day to play so I'm updating my drivers and will try to see if my (or any) resource pack is the cause. I use PueBDCraft but I'll check Faithful out for this.

**Comment by Geethebluesky** [comment] 2022-08-19 18:27
Ok, I just installed Forge with Optifine, versions 40.0.24 and OptiFine_1.18.2_HD_U_H7.jar (which states it supports that version of Forge), and the install was a pain in PolyMC but that's another issue. :)

I loaded your shader and with the default texture pack everything's fine. **I do see the rectangle** when I load either resource pack (PureBDCraft or Classic Faithful) however.

Does this help?

**Comment by TechDevOnGitHub** [comment] 2022-08-21 10:57
This did help, in fact, even though I couldn't properly reproduce this issue, but it very well might be related to https://github.com/TechDevOnGitHub/Lux-Shader/commit/da29b1f90d3695c0ac3ac7ed511acc04f67bd1d5.
I have pushed a potential fix for this issue now, so the dev version should work.

A quick yes or no if it works or not would be great.

**Comment by Geethebluesky** [comment] 2022-08-25 18:56
Hi, just had time to try this again and it works. Pretty enderman eyes! Thanks. :)

**Closed** 2022-08-26 20:21 UTC
Labels: bug, good first issue
